# Generated by Django 6.1.1 on 2026-09-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ADMIN', 'Administrador'), ('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente'), ('PRODUCCION', 'Jefe de Producción'), ('ALMACENISTA', 'Almacenista'), ('TERMINACION', 'Personal de Terminacion'), ('SECRETARIA', 'Secretaria')], default='PENDING', max_length=20),
        ),
    ]
