# Generated by Django 5.2.17 on 2026-09-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='document_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='requested_area',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('ADMIN', 'Administrador'), ('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente'), ('PRODUCCION', 'Jefe de Producción'), ('ALMACENISTA', 'Almacenista'), ('TERMINACION', 'Personal de Terminacion'), ('SECRETARIA', 'Secretaria')], max_length=20, null=True),
        ),
    ]
