# Generated by Django 5.2.17 on 2026-09-29 22:58

import apps.inventory.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'inventario_consecutivo',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('MATERIA_PRIMA', 'Materia prima'), ('INSUMO', 'Insumo'), ('GENERICO', 'Pantalón genérico'), ('TERMINADO', 'Producto terminado')], max_length=15)),
                ('unidad', models.CharField(choices=[('m', 'Metros'), ('kg', 'Kilogramos'), ('rollo', 'Rollos'), ('caja', 'Cajas'), ('unidad', 'Unidades')], max_length=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'inventario_producto',
                'ordering': ['tipo', 'nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('codigo',), name='uq_producto_codigo_activo'), models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='ck_producto_stock_no_negativo'), models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='ck_producto_minimo_no_negativo')],
            },
        ),
        migrations.CreateModel(
            name='OrdenSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('codigo', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('PRODUCCION', 'Producción'), ('LAVANDERIA', 'Lavandería')], max_length=12)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='EN_PROCESO', max_length=12)),
                ('fecha_salida', models.DateField()),
                ('responsable', models.CharField(max_length=120)),
                ('destino', models.CharField(blank=True, max_length=120)),
                ('ficha_tecnica', models.CharField(max_length=60)),
                ('cantidad_prendas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('completada_at', models.DateTimeField(blank=True, null=True)),
                ('anulada_at', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=255)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producto_resultado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_resultado', to='inventory.producto')),
            ],
            options={
                'db_table': 'inventario_orden',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='inventory.ordensalida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.producto')),
            ],
            options={
                'db_table': 'inventario_orden_linea',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida')], max_length=8)),
                ('motivo', models.CharField(choices=[('COMPRA', 'Compra a proveedor'), ('RETORNO_ORDEN', 'Retorno de una orden'), ('SALIDA_ORDEN', 'Salida por orden'), ('ANULACION', 'Anulación de orden')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_antes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_despues', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('orden_compra', models.CharField(blank=True, max_length=40)),
                ('lote', models.CharField(blank=True, max_length=60)),
                ('observaciones', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.ordensalida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.producto')),
            ],
            options={
                'db_table': 'inventario_movimiento',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archivo', models.FileField(upload_to=apps.inventory.models._evidence_path)),
                ('nombre_original', models.CharField(max_length=120)),
                ('content_type', models.CharField(max_length=40)),
                ('tamano', models.PositiveIntegerField()),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='inventory.movimiento')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='inventory.ordensalida')),
            ],
            options={
                'db_table': 'inventario_evidencia',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('movimiento__isnull', False), ('orden__isnull', True)), models.Q(('movimiento__isnull', True), ('orden__isnull', False)), _connector='OR'), name='ck_evidencia_un_solo_dueno')],
            },
        ),
        migrations.AddConstraint(
            model_name='ordensalida',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('codigo',), name='uq_orden_codigo_activo'),
        ),
        migrations.AddConstraint(
            model_name='ordenlinea',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_orden_linea_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='ordenlinea',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('orden', 'producto'), name='uq_orden_linea_producto'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['producto', '-created_at'], name='ix_mov_producto_fecha'),
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_movimiento_cantidad_positiva'),
        ),
    ]
