# Generated by Django 5.2.17 on 2026-09-30 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        # El texto libre que había en `proveedor` pasa a ser el nombre guardado al momento
        # de la compra; `proveedor` se vuelve la llave al proveedor real (más abajo).
        migrations.RenameField(
            model_name='movimiento',
            old_name='proveedor',
            new_name='proveedor_nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho_util',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('TELA', 'Telas y tejidos denim'), ('HILO', 'Hilos e hilazas de confección'), ('CIERRE', 'Cremalleras y cierres'), ('BOTON_REMACHE', 'Botones metálicos y remaches'), ('ETIQUETA_EMPAQUE', 'Etiquetas, marquillas y empaque'), ('QUIMICO', 'Químicos de lavandería'), ('OTRO_INSUMO', 'Otros insumos'), ('PANTALON_GENERICO', 'Pantalón genérico (en crudo)'), ('PRODUCTO_TERMINADO', 'Producto terminado')], max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='producto',
            name='composicion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_tipo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('m', 'Metros'), ('kg', 'Kilogramos'), ('l', 'Litros'), ('rollo', 'Rollos'), ('caja', 'Cajas'), ('unidad', 'Unidades')], max_length=10),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nit', models.CharField(max_length=10)),
                ('nit_dv', models.CharField(blank=True, max_length=1)),
                ('razon_social', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('TELA', 'Telas y tejidos denim'), ('HILO', 'Hilos e hilazas de confección'), ('CIERRE', 'Cremalleras y cierres'), ('BOTON_REMACHE', 'Botones metálicos y remaches'), ('ETIQUETA_EMPAQUE', 'Etiquetas, marquillas y empaque'), ('QUIMICO', 'Químicos de lavandería'), ('OTRO_INSUMO', 'Otros insumos')], max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=120)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'inventario_proveedor',
                'ordering': ['razon_social'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('nit',), name='uq_proveedor_nit_activo')],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.proveedor'),
        ),
    ]
